age=65
print(age)
a=10
print(a)
_=20
print(_)
_=_+1
print(_)
#print
abc123=78
_pramod="amit"
pi=3.14
print(pi)
print(type(pi))
print(type(_pramod))
complex_number=2+3j
print(complex_number)
print(type(complex_number.real))
print(type(complex_number.imag))
print(complex_number.real)
print(complex_number.imag)
print(type(complex_number))
